--  Copyright 2025 TecOnca Data Solutions.

SELECT 
    TRF_ALU_ID,
    TRF_DT_ATUALIZACAO,
    TRF_DT_CRIACAO,
    TRF_ESC_ID_DESTINO,
    TRF_ESC_ID_ORIGEM,
    TRF_ID,
    TRF_JUSTIFICATIVA,
    TRF_OLD_ID,
    TRF_STATUS,
    TRF_TUR_ID_DESTINO,
    TRF_TUR_ID_ORIGEM,
    TRF_USU,
    TRF_USU_STATUS
FROM Saev.transferencia
