# Copyright 2025 TecOnca Data Solutions.


# Lista de tabelas para ingestão
tables:
{% for table in database['tables'] -%}
  - name: {{ table['table'] }}
  query_file: {{ table['table'] }}.sql
  schema_file: {{ table['table'] }}.json
  delta_config:
    column: GEN_DT_ATUALIZACAO
    type: TIMESTAMP
  merge_config:
    keys:
      - GEN_ID
  partitioning_config:
    type: DAY
    column: GEN_DT_ATUALIZACAO
  clustering_config:
    columns: 
      - GEN_ID
      - GEN_ATIVO

{% endfor -%}