# Copyright 2025 TecOnca Data Solutions.


# Lista de tabelas para ingestão
tables:
{% for tables in database['tables'] -%}
  - name: {{ tables['table'] }}
  query_file: {{ tables['table'] }}.sql
  schema_file: {{ tables['table'] }}.json
  {%- if tables['field_where'] %}
  delta_config:
    column: {{ tables['field_where'][0] }}
    format: '{{ tables['field_where'][1] }}'
    type: {{ tables['field_where'][2] }}
  {%- endif %}
  {%- if tables['primary_keys'] | length <= 1 -%}
  {% for unique_key in tables['primary_keys'] | unique %}
  read_partitioning_config:
    column: {{ unique_key }}
    num_partitions: 1
  {%- endfor %}
  {%- endif -%}
  {%- if tables['primary_keys'] %}
  merge_config:
    strategy: 'upsert' #'upsert' or 'scd2'
    keys:
    {%- for key in tables['primary_keys'] | unique %}
      - {{ key }}
    {%- endfor %}
  {%- endif -%}
  {%- if tables['partition_id'] %}
  partitioning_config:
    type: {{ tables['partition_id'][1] }}
    column: {{ tables['partition_id'][0] }}
  {%- endif %}
  {%- if tables['primary_keys'] %}
  clustering_config:
    columns: 
    {%- set keys = tables['primary_keys'] + tables['unique_keys'] %}
    {%- set filter_keys = keys | unique | slice(4) %}
    {%- for key in filter_keys %}
      {%- if key %}
      - {{ key[0] }}
      {%- endif -%}
    {% endfor %}
  {% endif %}
{% endfor -%}