# Copyright 2025 TecOnca Data Solutions.


# Lista de tabelas para ingestão
tables:
{% for tables in database['tables'] -%}
  - name: {{ tables['table'] }}
  query_file: {{ tables['table'] }}.sql
  schema_file: {{ tables['table'] }}.json
  delta_config:
    column: {{ tables['field_where'][0] }}
    format: '{{ tables['field_where'][1] }}'
    type: {{ tables['field_where'][2] }}
  merge_config:
    keys:
    {% for key in tables['primary_keys'] | unique | sort -%}
      - {{ key[0] }}
    {% endfor %}
  partitioning_config:
    type: DAY
    column: {{ tables['field_where'][0] }}
  clustering_config:
    columns: 
    {% for key in tables['primary_keys'] | unique | sort -%}
      - {{ key[0] }}
    {% endfor %}
{% endfor -%}