# Copyright 2025 TecOnca Data Solutions.


# Lista de tabelas para ingestão
tables:
{% for table in database['tables'] -%}
  - name: {{ table['table'] }}
  {% for fields in table['fields_details'] -%}
  query_file: {{ table['table'] }}.sql
  schema_file: {{ table['table'] }}.json
  delta_config:
    column: GEN_DT_ATUALIZACAO
    format: '%Y-%m-%d %H:%i:%s.%f'
    type: TIMESTAMP
  merge_config:
    keys:
      - GEN_ID
  partitioning_config:
    type: DAY
    column: GEN_DT_ATUALIZACAO
  clustering_config:
    columns: 
      - GEN_ID
      - GEN_ATIVO

  {%- endfor %}
  
{% endfor -%}

